# Model configuration
model:
  is_rec: True
  episode_length: 30
  diff: True
  hidden_size: 30

env:
  radius: 2.0

# iterations and other batch parameters
log:
  runs: 3
  iterations: 5000
  average_every: 50
  reset_every: 1
  save_every: 100
  eval_every: 50


# SPSA Parameters
SPSA:
  n_workers: 16
  a: 1e-2 
  c: 1e-1
  k: 100
  A: 10
  alpha: 1e-1
  gamma: 1e-1
  noise: 0
  decay: 0
  lr_decay: 0
  momentum: 0.9
  noise: 0.0
  decay: 0
  n_evals: 1