# Model configuration
model:
  hidden_size: 30
  is_rec: True
  episode_length: 30
  diff: False

# iterations and other batch parameters
log:
  runs: 1
  iterations: 2000
  average_every: 50
  reset_every: 1
  save_every: 100
  eval_every: 100


# SPSA Parameters
SPSA:
  n_workers: 16
  a: 1e-2
  c: 1e-1
  k: 10
  A: 10
  alpha: 5e-2
  gamma: 1e-3
  noise: 0
  decay: 0
  lr_decay: 0
  momentum: 0.0
  noise: 0.0
  decay: 0
  n_evals: 100